[build]
# Customize the build command
cmd = "go build -o ./tmp/main cmd/translators/main.go"
# Customize the binary name
bin = "./tmp/main"
# Watch these directories for changes
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]

[log]
# Customize the log color
color = "true"